#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/cebooklub
#    username: cebooklub
#    password: cebooklub
#  sql:
#    init:
#      mode: always
#  jpa:
#    hibernate:
#      ddl-auto: update